revert to the last build that ran to smoke test for the config.yml only

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,4 @@
 version: 2.1
-
 commands:
   install_awscli:
     description: Install AWS cli
@@ -10,7 +9,6 @@ commands:
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
-
   install_nodejs:
     description: Install Node.js 13
     steps:
@@ -19,7 +17,6 @@ commands:
           command: |
             curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
             sudo apt install -y nodejs
-
   install_ansible:
     description: Install Ansible
     steps:
@@ -30,7 +27,6 @@ commands:
             sudo apt install software-properties-common -y
             sudo add-apt-repository --yes --update ppa:ansible/ansible
             sudo apt install ansible -y
-
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
@@ -60,14 +56,12 @@ commands:
           when: on_fail
           command: |
             SUCCESS=$(curl --insecure https://kvdb.io/FdEQLyzPWSP4VAfFxD48KY/migration_${CIRCLE_WORKFLOW_ID:0:7})
-
             if(( $SUCCESS==1 ));
             then
               cd ~/project/backend
               npm install
               npm run migration:revert
             fi
-
 jobs:
   build-frontend:
     docker:
@@ -82,11 +76,9 @@ jobs:
             cd frontend
             npm install
             npm run build
-
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
-
   build-backend:
     docker:
       - image: circleci/node:13.8.0
@@ -100,11 +92,9 @@ jobs:
             cd backend
             npm install
             npm run build
-
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
-
   test-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -131,7 +121,6 @@ jobs:
             cd backend
             npm install
             npm test
-
   scan-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -146,7 +135,6 @@ jobs:
             npm install
             npm audit fix --audit-level=critical --force
             npm audit --audit-level=critical
-
   scan-backend:
     docker:
       - image: circleci/node:13.8.0
@@ -162,7 +150,6 @@ jobs:
             npm audit fix --audit-level=critical --force
             npm audit fix --force --audit-level=critical
             npm audit --audit-level=critical
-
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
@@ -182,7 +169,6 @@ jobs:
             --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
             --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
             --tags project=udapeople
-
       - run:
           name: Ensure front-end infrastructure exist
           command: |
@@ -191,7 +177,6 @@ jobs:
             --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
             --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
             --tags project=udapeople
-
       - run:
           name: Add back-end ip to ansible inventory
           command: |
@@ -202,18 +187,14 @@ jobs:
             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
             --query 'Reservations[*].Instances[*].PublicIpAddress' \
             --output text)
-
             echo "${BACKEND_IP}" >> .circleci/ansible/inventory.txt
-
             cat .circleci/ansible/inventory.txt
-
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
       #  - destroy-environment
       # Here's where you will add some code to rollback on failure
-
   configure-infrastructure:
     docker:
       - image: python:3.10-alpine3.16
@@ -223,10 +204,8 @@ jobs:
           at: ~/
       - add_ssh_keys:
           fingerprints:
-            - "93:f8:05:5e:27:bb:99:d4:f1:73:87:d3:d6:94:5e:7a"
-
+            - "74:9d:14:cb:d2:35:1d:48:18:bb:75:f0:be:13:dd:93"
       # - install_ansible
-
       - run:
           name: Install dependencies
           command: |
@@ -240,10 +219,8 @@ jobs:
             cat inventory.txt
             ansible-playbook -i inventory.txt configure-server.yml
           # no_output_timeout: 30m
-
       - destroy-environment
       # Here's where you will add some code to rollback on failure
-
   run-migrations:
     docker:
       - image: circleci/node:13.8.0
@@ -268,7 +245,6 @@ jobs:
             echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
             echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
             echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
-
             cd backend
             npm install
             npm run migrations > migrations_dump.txt
@@ -276,27 +252,23 @@ jobs:
       - run:
           name: Send migration results to kvdb
           command: |
-
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
               curl https://kvdb.io/FdEQLyzPWSP4VAfFxD48KY/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1' 
             fi
       - destroy-environment
       - revert-migrations
-
   deploy-frontend:
     docker:
       - image: cimg/base:stable
-
     steps:
       # Checkout code from git
       - checkout
       - add_ssh_keys:
           fingerprints:
-            - "93:f8:05:5e:27:bb:99:d4:f1:73:87:d3:d6:94:5e:7a"
+            - "74:9d:14:cb:d2:35:1d:48:18:bb:75:f0:be:13:dd:93"
       - attach_workspace:
           at: ~/
-
       - install_nodejs
       - install_awscli
       - install_ansible
@@ -313,7 +285,6 @@ jobs:
             echo "API_URL = ${API_URL}"
             echo API_URL= "http://${BACKEND_IP}:3030" >> frontend/.env
             cat frontend/.env
-
       - run:
           name: Deploy frontend objects
           command: |
@@ -323,139 +294,80 @@ jobs:
             npm install
             npm run build
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-
       - destroy-environment
       - revert-migrations
-
       # Here's where you will add some code to rollback on failure
-
   deploy-backend:
     docker:
+      # Docker image here that supports Ansible
       - image: cimg/base:stable
     steps:
       - checkout
       - add_ssh_keys:
           fingerprints:
-            - "93:f8:05:5e:27:bb:99:d4:f1:73:87:d3:d6:94:5e:7a"
+            - "74:9d:14:cb:d2:35:1d:48:18:bb:75:f0:be:13:dd:93"
       - attach_workspace:
           at: ~/
-
       - install_nodejs
       - install_awscli
       - install_ansible
       - run:
           name: Deploy backend
           command: |
+            # your code here
             cd backend
             npm i
             npm run build  
             cd ..
-
             cd .circleci/ansible
             mkdir files
             cd files
             tar -C ../../../backend -czvf artifact.tar.gz .
             cd ../
-
             echo "Contents of the inventory.txt files is -------"
             cat inventory.txt
-
             ansible-playbook -i inventory.txt deploy-backend.yml
-
       - destroy-environment
       - revert-migrations
       # Here's where you will add some code to rollback on failure
-
-  # smoke-test:
-  #   docker:
-  #     - image: cimg/base:stable
-  #   steps:
-  #     - checkout
-
-  #     - install_nodejs
-  #     - install_awscli
-  #     - run:
-  #         name: Backend smoke test.
-  #         command: |
-  #           BACKEND_PUBLIC_IP=$(aws ec2 describe instances \
-  #             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-  #             --query "Reservations[*].Instances[*].PublicIpAddress" \
-  #             --output text)
-  #             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-  #             echo ${BACKEND_PUBLIC_IP}
-  #             echo backend-${CIRCLE_WORKFLOW_ID:0:7}
-  #             echo ${API_url}
-  #             if curl -s ${API_URL}/api/status | grep "ok"
-  #             then
-  #               exit 0
-  #             else
-  #               exit 1
-  #             fi
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-  #           echo ${FRONTEND_WEBSITE}
-  #           if curl -s ${FRONTEND_WEBSITE} | grep "Welcome"
-  #           then
-  #             exit 1
-  #           else
-  #             exit 1
-  #           fi
-  #     # - destroy-environment
-  #     # - revert-migrations
-  #     # Here's where you will add some code to rollback on failure
-
   smoke-test:
     docker:
-      - image: python:3.7-alpine3.11
+      - image: cimg/base:stable
     steps:
       - checkout
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            pip3 install awscli
-            apk add --update curl
-      # - run:
-      #     name: Get backend url
-      #     command: |
-      #       BACKEND_IP=$(aws ec2 describe-instances \
-      #         --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-      #         --query 'Reservations[*].Instances[*].PublicIpAddress' \
-      #         --output text)
+      - install_nodejs
+      - install_awscli
       - run:
           name: Backend smoke test.
           command: |
-            BACKEND_IP=$(aws ec2 describe-instances \
+            BACKEND_PUBLIC_IP=$(aws ec2 describe instances \
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --query "Reservations[*].Instances[*].PublicIpAddress" \
               --output text)
-
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
-            then
-                return 0
-            else
-                return 1
-            fi
+              export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+              echo ${BACKEND_PUBLIC_IP}
+              echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+              echo ${API_url}
+              if curl -s $API_URL/api/status | grep "ok"
+              then
+                exit 0
+              else
+                exit 1
+              fi
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
-            echo ${URL}
-            if curl -s ${URL} | grep "Welcome"
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            echo $FRONTEND_WEBSITE
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
             then
-                # Change this to 0 after the job fails
-              return 0
+              exit 1
             else
-              return 1
+              exit 1
             fi
       - destroy-environment
       - revert-migrations
-
+      # Here's where you will add some code to rollback on failure
   cloudfront-update:
     docker:
       - image: amazon/aws-cli
@@ -469,7 +381,7 @@ jobs:
             export OLD_WORKFLOW_ID=$(aws cloudformation \
             list-exports --query "Export[?Name==\`Workflow\`].Value" \
             --no-pagination --output text)
-            echo "Old Workflow ID: ${OLD_WORKFLOW}"
+            echo "Old Workflow ID: $OLD_WORKFLOW"
             curl https://kvdb.io//${FdEQLyzPWSP4VAfFxD48KY}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
       - run:
           name: Update cloudfront distribution
@@ -481,9 +393,7 @@ jobs:
             --stack-name InitialStack
       - destroy-environment
       - revert-migrations
-
       # Here's where you will add some code to rollback on failure
-
   cleanup:
     docker:
       # Docker image here
@@ -501,14 +411,13 @@ jobs:
                 --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
             echo Stack names: "${STACKS[@]}"
             export OldWorkflowID=$(curl --insucure https://kvdb.io/FdEQLyzPWSP4VAfFxD48KY/old_workflow_id)
-            echo Old Workfloe ID: ${OldWorkflowID}
+            echo Old Workfloe ID: $OldWorkflowID
             # export STACKS=[] #put the list of stacks here
       - run:
           name: Remove old stacks and files
           command: |
             export OldWorkflowID=$(curl --insecure https://kvdb.io/FdEQLyzPWSP4VAfFxD48KY/old_workflow_id)
-            echo Old Workflow ID: ${OldWorkflowID}
-
+            echo Old Workflow ID: $OldWorkflowID
             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
               # your code here
@@ -516,7 +425,6 @@ jobs:
               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
             fi
-
 workflows:
   default:
     jobs:
