to generate screenshot09

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -375,7 +375,7 @@ jobs:
             if curl -s ${URL} | grep "Welcome"
             then
                 # Change this to 0 after the job fails
-              exit 0
+              exit 1
             else
               exit 1
             fi
@@ -406,9 +406,10 @@ jobs:
             --template-file .circleci/files/cloudfront.yml \
             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
             --stack-name InitialStack
+      # Here's where you will add some code to rollback on failure
       - destroy-environment
       - revert-migrations
-      # Here's where you will add some code to rollback on failure
+
   cleanup:
     docker:
       # Docker image here
